---
title: dafuloth.me
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: single
    author_profile: true
    read_time: true
    comments: true
    share: true
    related: true
minimal_mistakes_skin: default
locale: en
title_separator: " :: "
name: David Thai
description: 'dafuloth.me is my personal blog, built on the Minimal Mistakes theme
  by Michael Rose. '
url: https://dafuloth.me
baseurl: 
repository: 
teaser: 
breadcrumbs: true
words_per_minute: 200
comments:
  provider: disqus
  disqus:
    shortname: dafuloth
  discourse:
    server: 
  facebook:
    appid: 
    num_posts: 
    colorscheme: 
staticman:
  allowedFields: 
  branch: 
  commitMessage: 
  filename: 
  format: 
  moderation: 
  path: 
  requiredFields: 
  transforms:
    email: 
  generatedFields:
    date:
      type: 
      options:
        format: 
reCaptcha:
  siteKey: 
  secret: 
atom_feed:
  path: 
search: 
search_full_content: 
search_provider: 
algolia:
  application_id: 
  index_name: 
  search_only_api_key: 
  powered_by: 
google:
  search_engine_id: 
  instant_search: 
google_site_verification: 
bing_site_verification: 
yandex_site_verification: 
naver_site_verification: 
twitter:
  username: dafuloth
facebook:
  username: 
  app_id: 
  publisher: 
og_image: 
social:
  type: 
  name: 
  links: 
analytics:
  provider: google
  google:
    tracking_id: UA-50002010-2
    anonymize_ip: false
author:
  name: David Thai
  avatar: "/assets/images/infinity.png"
  bio: A simple site where I can focus on what matters
  location: London, UK
  email: 
  uri: https://dafuloth.me
  home: 
  bitbucket: 
  codepen: 
  dribbble: 
  flickr: 
  facebook: 
  foursquare: 
  github: 
  gitlab: 
  google_plus: 
  keybase: 
  instagram: 
  lastfm: ethereal_shadow
  linkedin: 
  pinterest: 
  soundcloud: 
  stackoverflow: 
  steam: ilmarinen
  tumblr: 
  twitter: dafuloth
  vine: 
  weibo: 
  xing: 
  youtube: 
include:
- ".htaccess"
- _pages
exclude:
- "*.sublime-project"
- "*.sublime-workspace"
- vendor
- ".asset-cache"
- ".bundle"
- ".jekyll-assets-cache"
- ".sass-cache"
- assets/js/plugins
- assets/js/_main.js
- assets/js/vendor
- Capfile
- CHANGELOG
- config
- Gemfile
- Gruntfile.js
- gulpfile.js
- LICENSE
- log
- node_modules
- package.json
- Rakefile
- README
- tmp
- "/docs"
- "/test"
keep_files:
- ".git"
- ".svn"
encoding: utf-8
markdown_ext: markdown,mkdown,mkdn,mkd,md
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed
permalink: pretty
paginate: 5
paginate_path: "/page:num/"
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
whitelist:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
category_archive:
  type: liquid
  path: "/categories/"
tag_archive:
  type: liquid
  path: "/tags/"
compress_html:
  clippings: all
  ignore:
    envs: development
